name: image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/matopst/debug-pod

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6

      - name: Set BUILD_VERSION
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push image with Ko
        run: |
          echo "Publishing image as: $IMAGE_NAME:$BUILD_VERSION"
          KO_DOCKER_REPO=${{ env.IMAGE_NAME }} ko publish . --bare -t $BUILD_VERSION